language: node_js
node_js:
 - "stable"
cache:
directories:
 - node_modules
script:
 - npm test
 - npm run build
before_deploy: pip install --user awscli
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync build s3://superflower.website --delete      
  skip_cleanup: true
  on:
    branch: main
